# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21dde06f71b0f66a5145ca6a0bc9c1050a49554e989e5c0a8671ccfcd17fa8de8e850ad5a18a80a7a9fa01cf3b1cc3c1fc9de606bda0c2f8c7f49e9b5570bbdb

test:
  secret_key_base: 557ff344d14fb0be901d85aa7d4c7187ee536fd0cca1a39effba57a11ea1b466ec36434c36083a25af4d6ef9f48c4b40b78157f93c1cee0ba10dcdf71dac43b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
